### ISSUE TITLE
Архитектурно неверный подход

### ISSUE THREAD

**Issue by SimonOsipov** [pgerasimov/books_search#10]
https://github.com/pgerasimov/books_search/blob/8a1a3e54ac762562c93d853c52f77892565670ae/webapp/__init__.py#L122-L134

Зачем делать запрос со всеми книгами, а затем пробегаться по нему?
У тебя есть название книги. Сделай запрос к базе, используя SQL Like нотацию https://stackoverflow.com/questions/3325467/sqlalchemy-equivalent-to-sql-like-statement

**Comment by sergiishevchenko** [comment]
ревью данного кода уже не актуально) я этот код заливал ещё до того, как Павел предложил рабочий вариант.
