### ISSUE TITLE
Редирект со страницы поиска на страницу книги

### ISSUE THREAD

**Issue by SimonOsipov** [pgerasimov/books_search#15]
Добавить ссылки на индивидуальные странцы книги со страницы поиска

**Comment by sergiishevchenko** [comment]
https://github.com/pgerasimov/books_search/blob/098bbe87444b8d463b5a2fd3d3a35076becaa2fb/webapp/__init__.py#L126-L127 Done.

**Comment by sergiishevchenko** [comment]
Done.https://github.com/pgerasimov/books_search/blob/837e41022bd298c82a2866d8ae7946a22c46c636/webapp/__init__.py#L133-L145
https://github.com/pgerasimov/books_search/blob/837e41022bd298c82a2866d8ae7946a22c46c636/webapp/templates/search_result.html#L14
https://github.com/pgerasimov/books_search/blob/837e41022bd298c82a2866d8ae7946a22c46c636/webapp/templates/book.html#L12-L13
