### ISSUE TITLE
А почему это здесь?)

### ISSUE THREAD

**Issue by SimonOsipov** [pgerasimov/books_search#18]
https://github.com/pgerasimov/books_search/blob/4f65bb9d0207d56249fdb9603155aee24c39aa7c/webapp/find_book.py#L47-L48

**Comment by pgerasimov** [comment]
Другим способом не получилось получить доступ к базе данных, пока не знаю как сделать иначе

**Comment by SimonOsipov** [comment]
Как минимум, все импорты должны быть в самом верху файла

**Comment by pgerasimov** [comment]
https://github.com/pgerasimov/books_search/commit/72b8a5f5b3fd3c650100f2fa8b33229d01fd0d4c
