### ISSUE TITLE
Ошибки не должны управлять логикой

### ISSUE THREAD

**Issue by SimonOsipov** [pgerasimov/books_search#19]
https://github.com/pgerasimov/books_search/blob/4f65bb9d0207d56249fdb9603155aee24c39aa7c/webapp/find_book.py#L60

То есть, нельзя на появление ошибки завязывать какой-то процесс.
И еще нельзя, чтобы ошибка происходила в тишине. То есть произошла и хер бы с ней

**Comment by pgerasimov** [comment]
https://github.com/pgerasimov/books_search/commit/db366c9bee725b1e8daecdd8a53d95ece7f92ef3
