### ISSUE TITLE
Ваши контакты в описании

### ISSUE THREAD

**Issue by SimonOsipov** [pgerasimov/books_search#2]
Сделайте ссылки на ваши гитхабы / почту / линкедины в разделе контакты.
Сейчас там только ники)

**Comment by sergiishevchenko** [comment]
Done. https://github.com/pgerasimov/books_search/blob/dev/README.md

**Comment by SimonOsipov** [comment]
@sergiishevchenko Лучше давать ссылку на хеш коммита
