### ISSUE TITLE
Порядок действий

### ISSUE THREAD

**Issue by SimonOsipov** [pgerasimov/books_search#6]
https://github.com/pgerasimov/books_search/blob/bff9e0c0e2f23ed11fdf7b06de9e91bc9283dbe2/webapp/__init__.py#L61-L73

Получи **все** данные
Проверь
Действую

**Comment by sergiishevchenko** [comment]
https://github.com/pgerasimov/books_search/blob/727a52d885d5e86b90428b6216236c71280087f0/webapp/__init__.py#L58-L73
исправил
